cmd /c "dir"
cmd /c "systeminfo"
cmd /c "mountvol"
cmd /c "echo list disk | diskpart"
cmd /c "echo list volume | diskpart"
cmd /c "where 7z"
cmd /c "cd /d c:\ & echo a > a & 7z a logs.zip a"
cmd /c "dir c:\"
