jobs:
  build:
    machine:
      image: ubuntu-2004:current
    resource_class: arm.large
    environment:
      TERMUX_PREFIX: /data/data/com.termux/files/usr
      TERMUX_HOME: /data/data/com.termux/files/home
      PIP_DISABLE_PIP_VERSION_CHECK: 1
    steps:
      - run:
          name: Restore ccache Cache
          command: |
            mkdir -p archives; cd archives
            f=ccache.tar.xz
            curl --fail --output ${f} http://${MY_HOST}/${f} || true
      - run:
          name: get termux
          command: |
            mkdir -p archives; cd archives
            wget -nv https://github.com/kawanakaiku/test-ci/releases/download/chroot-termux/termux-aarch64.tar.xz
      - run:
          name: extract termux
          command: |
            mkdir termux-root
            for tar_xz in archives/*.tar.xz; do
              tar xf "${tar_xz}" -C termux-root
            done
      - run:
          name: chroot termux
          command: |
            cd termux-root
            
            mkdir -p proc dev dev/pts sys
            sudo mount -t proc proc proc
            sudo mount -t devtmpfs udev dev
            sudo mount -t devpts devpts dev/pts
            sudo mount -t sysfs sysfs sys
            
            # set host file
            mkdir -p system/etc
            for host in pypi.python.org files.pythonhosted.org pypi.org \
              github.com objects.githubusercontent.com \
              packages.termux.dev
            do
              echo $( nslookup $host | awk '/^Address: / { print $2; exit }' ) " $host" >> system/etc/hosts
            done
            
            # suppress linker: Warning: failed to find generated linker configuration from "/linkerconfig/ld.config.txt"
            mkdir -p linkerconfig
            touch linkerconfig/ld.config.txt
            
            TERMUX_USER=$( sudo chroot . /system/bin/stat -c '%U' ${TERMUX_PREFIX}/bin/env )
            TERMUX_GROUP=$( sudo chroot . /system/bin/stat -c '%G' ${TERMUX_PREFIX}/bin/env )
          
            sudo ls -lha data/data/com.termux/files/usr/bin/env
            sudo chroot . ${TERMUX_PREFIX}/bin/env PATH=${TERMUX_PREFIX}/bin ls -lha /data/data/com.termux/files/usr/bin/env
            
            cat <<SH > /tmp/chroot
            #!/usr/bin/sh
            exec sudo chroot ${PWD} \
              ${TERMUX_PREFIX}/bin/su ${TERMUX_USER} \
              ${TERMUX_PREFIX}/bin/env \
              PATH=${TERMUX_PREFIX}/bin \
              HOME=${TERMUX_HOME} \
              PREFIX=${TERMUX_PREFIX} \
              LANG=en_US.UTF-8 \
              PIP_DISABLE_PIP_VERSION_CHECK=1 \
              "\$@"
            SH
            chmod +x /tmp/chroot

            /tmp/chroot bash <<BASH
            apt-get update
            apt-get upgrade -y build-essential cmake ninja ccache libopenblas python-numpy
            BASH
      - run:
          name: clone
          command: |
            # get src to termux-root/python/torch
            mkdir termux-root/python
            cd termux-root/python
            wget -nv -O pytorch.tar.gz https://github.com/kawanakaiku/test-ci/releases/download/src/torch-v1.12.1.tar.xz
            tar xf pytorch.tar.gz

            # patch src
            cd torch
            sed -i -e 's/**build_options,/**build_options | {i: j for i, j in [i.strip().split("=", 1) for i in os.getenv("cmake_args").split(os.linesep) if "=" in i]},/' tools/setup_helpers/cmake.py
            find . -name CMakeLists.txt -o -name '*.cmake' | \
              xargs -n 1 sed -i \
              -e 's/\([^A-Za-z0-9_]ANDROID\)\([^A-Za-z0-9_]\)/\1_NO_TERMUX\2/g' \
              -e 's/\([^A-Za-z0-9_]ANDROID\)$/\1_NO_TERMUX/g'
            curl -s https://raw.githubusercontent.com/kawanakaiku/termux-packages/master/packages/python-pkgs/torch.patch_python |
            sed -e "s%\@TERMUX_PREFIX\@%${TERMUX_PREFIX}%g" | patch --silent -p1
            #find . -type f -exec grep -Iq . {} \; -print | xargs -d'\n' sed -i -e 's|__APPLE__|__SKIP_APPLE__|g'
            sed -i -e 's|BUILD_PYTHON|__IGNORE_BUILD_PYTHON|g' CMakeLists.txt
      - run:
          name: build
          command: |
            cd termux-root
            timeout --kill-after=0 --signal=SIGINT 50m /tmp/chroot bash <<CHROOT || true
            cd /python
            python3 -m pip wheel -r <( grep -v -e numpy torch/requirements.txt ) pip wheel setuptools
            python3 -m pip install *.whl

            pushd torch
            
            export AS=aarch64-linux-android-clang
            export CC=aarch64-linux-android-clang
            export CXX=aarch64-linux-android-clang++
            export LD=ld.lld
            export AR=llvm-ar
            export NM=llvm-nm
            export OBJCOPY=llvm-objcopy
            export OBJDUMP=llvm-objdump
            export RANLIB=llvm-ranlib
            export READELF=llvm-readelf
            export STRIP=llvm-strip
            export CFLAGS=" -fstack-protector-strong -Oz"
            export CXXFLAGS=" -fstack-protector-strong -Oz"
            export CPPFLAGS=" -I/data/data/com.termux/files/usr/include"
            export LDFLAGS="-L/data/data/com.termux/files/usr/lib -Wl,-rpath=/data/data/com.termux/files/usr/lib -fopenmp -static-openmp -Wl,--enable-new-dtags -Wl,--as-needed -Wl,-z,relro,-z,now"

            export cmake_args="
              ANDROID_NO_TERMUX=0
              BUILD_TEST=0
              BUILD_PYTHON=1
              BUILD_LAZY_TS_BACKEND=0
              C10_MOBILE=1
              BUILD_CAFFE2_MOBILE=1
            "
            export LDFLAGS+=" -llog"
            export LDFLAGS+=" -lc -lm -lc++_shared"
            export LDFLAGS+=" -lpython3.10"
            python3 setup.py bdist_wheel
            mv dist/*.whl ..
            popd
            CHROOT
      - run:
          name: post build
          command: |
            /tmp/chroot bash <<CHROOT || true
            cd /python
            pip install torch-*.whl
            #ln -s ${PREFIX}/lib/python3.10/site-packages/torch/lib/*.so ${PREFIX}/lib
            python -c 'import torch'
            CHROOT
      - run:
          name: archive ccache
          command: |
            tar -c -I 'xz -T0' -f archives/ccache.tar.xz -C termux-root ${TERMUX_HOME:1}/.cache/ccache
      - run:
          name: archive wheels
          command: |
            mv termux-root/python/*.whl .
            tar -c -I 'xz -T0' -f build.tar.xz *.whl
      - run:
          name: save ccache cache
          command: |
            curl -X POST http://${MY_HOST}/upload -F files=@archives/ccache.tar.xz
      - run:
          name: save artifact
          command: |
            curl -X POST http://${MY_HOST}/upload -F files=@build.tar.xz
            
