name: android-ndk-gfortran4

on:
    push:
      branches: [ main ]
      paths:
        - '.github/workflows/android-ndk-gfortran4.yml'
    workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-22.04
  
    steps:
      - name: info
        run: |
          df -h
          
      - name: prepare repo
        run: |
          mkdir -p ~/bin
          wget -nv https://storage.googleapis.com/git-repo-downloads/repo -O ~/bin/repo
          chmod a+x ~/bin/repo
          ~/bin/repo --version
          
      - name: clone
        run: |
          ~/bin/repo init --depth=1 -u https://android.googlesource.com/platform/manifest -b gcc
          ~/bin/repo sync
          ~/bin/repo forall -c git checkout ndk-r25-release || true
          
      - name: patch
        run: |
          perl -i -pe 's|\QENABLE_LANGUAGES="c,c++"\E|ENABLE_LANGUAGES="c,c++,fortran"|' toolchain/gcc/build-gcc.sh
          
          sed -i -e '/^setup_default_log_file /d' $( find -name build-gcc.sh -type f )  # build-gcc.sh: line 92: setup_default_log_file: command not found
          
      - name: prepare docker
        run: |
          # https://android.googlesource.com/platform/ndk/+/master/docs/Building.md
          
          cat <<'DOCKER' >Dockerfile
          FROM ubuntu:trusty
          RUN apt-get update
          RUN apt-get install -y build-essential curl flex git make pbzip2 texinfo uuid-runtime zip bison m4 zlib1g-dev libssl-dev && \
              apt-get clean
          RUN mkdir /tmp/python && cd /tmp/python && \
              curl https://www.python.org/ftp/python/3.6.8/Python-3.6.8.tar.xz -o python.tar.xz && \
              tar -Jxf python.tar.xz --strip-components=1 && \
              ./configure && make install && ln -s python3.6 /usr/local/bin/python && \
              cd / && rm -rf /tmp/python
          ENV CC gcc
          RUN ["/bin/bash"]
          DOCKER
          
          docker build -t ndk-dev ./
          
      - name: build
        run: |
          docker run -u $UID -v $PWD:/src -w /src ndk-dev toolchain/gcc/build.py \
            --host linux \
            --toolchain aarch64-linux-android
                    
      - name: archive
        run: |
          tar -Jcf build.tar.xz
          
      - name: store
        uses: actions/upload-artifact@v3
        with:
          name: android-ndk-gfortran
          path: build.tar.xz
