name: android-pxview

on:
    push:
      branches: [ main ]
      paths:
        - '.github/workflows/android-pxview.yml'
    workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-22.04
  
    steps:
      - name: clone
        run: |
          git clone https://github.com/kawanakaiku/pxview.git .

      - name: build
        run: |
          yarn install

          # https://zenn.dev/aryzae/articles/80ec1fe9d72db3  
          sed -i -e "s@com.android.tools.build:gradle:3.5.3@com.android.tools.build:gradle:4.2.1@g" android/build.gradle
          sed -i -e "s@6.2@6.9@g" android/gradle/wrapper/gradle-wrapper.properties
       
          # disable googleservices
          sed -i -E "s@^(apply plugin: 'com\.google\.)@// \1@g" android/app/build.gradle
          
          # ERROR:/home/runner/.gradle/caches/transforms-3/e7832e2a7b23290ed97a51474f1d95d0/transformed/appcompat-1.0.2/res/values-v26/values-v26.xml:5:5-8:13: AAPT: error: resource android:attr/colorError not found.
          # https://github.com/luggit/react-native-config/issues/299
          # sed -i -E "s@^(apply plugin: 'com\.google\.)@// \1@g" android/app/build.gradle
          # awk -i inplace 'buildToolsVersion' android/app/build.gradle
          
          # https://stackoverflow.com/questions/62769564/error-unable-to-resolve-module-react-native-community-toolbar-android
          yarn add @react-native-community/toolbar-android
          
          # https://stackoverflow.com/questions/51807028/package-android-support-annotation-does-not-exist
          yarn add --dev jetifier
          yarn run jetify
          
          # put key
          echo "${{ secrets.KEY_JKS_BASE64 }}" | base64 -d > ${HOME}/key.jks
                    
          pushd android
          
          ./gradlew app:assembleRelease \
            -PPXVIEWR_RELEASE_STORE_FILE="${HOME}/key.jks" \
            -PPXVIEWR_RELEASE_STORE_PASSWORD="${{ secrets.PASSWORD }}" \
            -PPXVIEWR_RELEASE_KEY_ALIAS="key" \
            -PPXVIEWR_RELEASE_KEY_PASSWORD="${{ secrets.PASSWORD }}"
          # https://github.com/yamill/react-native-orientation/issues/396
            
          popd
          
          mkdir build
          find . -name "*.apk" -print0 | xargs -0 -I@ cp --verbose @ build
          
      - name: Store built file
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build
