name: android-ndk-gfortran4

on:
    push:
      branches: [ main ]
      paths:
        - '.github/workflows/android-ndk-gfortran4.yml'
    workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-22.04
  
    steps:
      - name: info
        run: |
          df -h
          
      - name: prepare repo
        run: |
          mkdir -p ~/bin
          wget -nv https://storage.googleapis.com/git-repo-downloads/repo -O ~/bin/repo
          chmod a+x ~/bin/repo
          ~/bin/repo --version
          
      - name: clone
        run: |
          ~/bin/repo init --depth=1 -u https://android.googlesource.com/platform/manifest -b gcc
          ~/bin/repo sync
          ~/bin/repo forall -c git checkout ndk-r25-release || true

      - name: prepare docker
        run: |
          docker build -t ndk-dev infra/docker
          docker run -it -u $UID -v `realpath ..`:/src -w /src/ndk ndk-dev ./checkbuild.py
          
      - name: build
        run: |
          # export CC=gcc  # Disable Forcing generation of linux binaries with legacy toolchain
          toolchain/gcc/build.py \
            --host linux \
            --toolchain aarch64-linux-android
                    
      - name: archive
        run: |
          tar -Jcf build.tar.xz
          
      - name: store
        uses: actions/upload-artifact@v3
        with:
          name: android-ndk-gfortran
          path: build.tar.xz
          
