name: android-ndk-gfortran3

on:
    push:
      branches: [ main ]
      paths:
        - '.github/workflows/android-ndk-gfortran3.yml'
    workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-20.04
  
    steps:
      - uses: actions/checkout@v3

      - name: info
        run: |
          df -h

      - name: prepare
        run: |
          echo "path-exclude=/usr/share/man/*" | sudo tee /etc/dpkg/dpkg.cfg.d/01_nodoc
          sudo apt-get update
          sudo apt-get upgrade -y git repo make gcc g++ m4 texinfo bison flex build-essential
          
      - name: clone
        run: |
          repo init --depth=1 -u https://android.googlesource.com/platform/manifest -b gcc
          repo sync
          repo forall -c git checkout ndk-r25-release || true
          
      - name: patch
        run: |
          perl -i -pe 's|\QENABLE_LANGUAGES="c,c++"\E|ENABLE_LANGUAGES="c,c++,fortran"|' toolchain/gcc/build-gcc.sh
                    
      - name: help
        run: |
          toolchain/gcc/build.py -h
                    
      - name: build
        run: |
          export CC=gcc  # Disable Forcing generation of linux binaries with legacy toolchain
          toolchain/gcc/build.py \
            --host linux \
            --toolchain aarch64-linux-android
                    
      - name: archive
        run: |
          tar -Jcf build.tar.xz
          
      - name: store
        uses: actions/upload-artifact@v3
        with:
          name: android-ndk-gfortran
          path: build.tar.xz
          
