name: android-ndk-gfortran3

on:
    push:
      branches: [ main ]
      paths:
        - '.github/workflows/android-ndk-gfortran3.yml'
    workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-22.04
  
    steps:
      - uses: actions/checkout@v3

      - name: info
        run: |
          env | sort
          exit 1
          df -h

      - name: prepare
        run: |
          echo "path-exclude=/usr/share/man/*" | sudo tee /etc/dpkg/dpkg.cfg.d/01_nodoc >/dev/null
          echo 'Acquire::Languages "none";' | sudo tee /etc/apt/apt.conf.d/99_translations >/dev/null
          sudo apt-get update
          sudo apt-get install -y git make gcc g++ m4 texinfo bison flex build-essential

      - name: prepare repo
        run: |
          mkdir -p ~/bin
          wget -nv https://storage.googleapis.com/git-repo-downloads/repo -O ~/bin/repo
          chmod a+x ~/bin/repo
          ~/bin/repo --version
          
      - name: clone
        run: |
          ~/bin/repo init --depth=1 -u https://android.googlesource.com/platform/manifest -b gcc
          ~/bin/repo sync
          ~/bin/repo forall -c git checkout ndk-r25-release || true
          
      - name: patch
        run: |
          perl -i -pe 's|\QENABLE_LANGUAGES="c,c++"\E|ENABLE_LANGUAGES="c,c++,fortran"|' toolchain/gcc/build-gcc.sh
          
          sed -i -e '/^setup_default_log_file /d' $( find -name build-gcc.sh -type f )  # build-gcc.sh: line 92: setup_default_log_file: command not found
                    
      - name: help
        run: |
          toolchain/gcc/build.py -h
                    
      - name: build
        run: |
          # export CC=gcc  # Disable Forcing generation of linux binaries with legacy toolchain
          toolchain/gcc/build.py \
            --host linux \
            --toolchain aarch64-linux-android
                    
      - name: archive
        run: |
          tar -Jcf build.tar.xz
          
      - name: store
        uses: actions/upload-artifact@v3
        with:
          name: android-ndk-gfortran
          path: build.tar.xz
          
