name: android-go

on:
    push:
      branches: [ main ]
      paths:
        - '.github/workflows/android-go.yml'
    workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-22.04
  
    steps:
        - name: Install Gomobile
          run: |
            go install golang.org/x/mobile/cmd/gomobile@latest
            go install golang.org/x/mobile/cmd/gobind@latest
            go get golang.org/x/mobile/cmd/gobind
            go get golang.org/x/mobile/cmd/gomobile
            gomobile init -v
          env:
            GOPROXY: https://proxy.golang.org,direct
            GO111MODULE: "on"

        - name: Go Mobile build
          run: |
            $HOME/go/bin/gomobile build golang.org/x/mobile/example/basic

        - name: Store built file
          if: always()
          uses: actions/upload-artifact@v3
          with:
            name: build
            path: basic.apk


