name: android-box86

on:
    push:
      branches: [ main ]
      paths:
        - '.github/workflows/android-box86.yml'
    workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v3

      - name: Run a multi-line script
        run: |
          echo "path-exclude=/usr/share/man/*" | sudo tee /etc/dpkg/dpkg.cfg.d/01_nodoc
          sudo apt-get update
          sudo apt-get -y --no-install-recommends install git cmake make python3 file
          git clone https://github.com/ptitSeb/box86.git box86
          wget -nv https://dl.google.com/android/repository/android-ndk-r23b-linux.zip
          unzip android-ndk-r23b-linux.zip

          BOX86_COMPILER=$PWD/android-ndk-r23b/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi31-clang
          BOX86_PLATFORM_MARCRO="-DANDROID=1 -DNOLOADADDR=1"
          BOX86_BUILD_TYPE=Release
          BOX86_HAVE_TRACE=0
  
          mkdir build
          cd build
          cmake .. -DCMAKE_C_COMPILER=${BOX86_COMPILER} \
                   ${BOX86_PLATFORM_MARCRO} \
                   -DCMAKE_BUILD_TYPE=${BOX86_BUILD_TYPE} \
                   -DHAVE_TRACE=${BOX86_HAVE_TRACE} \
                   -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON
          make -j$(nproc) VERBOSE=1
          
          # find ${HOME}/wine-build -type f | xargs file | awk -F: '$2 ~ /not stripped/ {print $1}' | xargs strip --strip-all --verbose
                    
      - name: built file info
        run: |
          file box86/build/box86
          sha256sum box86/build/box86

      - name: Store built file
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: android-box86
          path: box86/build/box86
          
