name: android-ndk-gfortran2

on:
    push:
      branches: [ main ]
      paths:
        - '.github/workflows/android-ndk-gfortran2.yml'
    workflow_dispatch:
    
env:
  binutils_version: 2.24
  gcc_version: 4.8.2
 
jobs:
  build:
    runs-on: ubuntu-22.04
  
    steps:
      - uses: actions/checkout@v3

      - name: prepare
        run: |
          echo "path-exclude=/usr/share/man/*" | sudo tee /etc/dpkg/dpkg.cfg.d/01_nodoc
          sudo apt-get update
          sudo apt-get install -y build-essential libgmp-dev libmpfr-dev libmpc-dev linux-libc-dev
          mkdir /tmp/prefix
          
      - name: clone1
        run: |
          wget -nv http://ftp.gnu.org/gnu/binutils/binutils-${binutils_version}.tar.xz
          tar xf binutils-${binutils_version}.tar.xz
                    
      - name: build1
        run: |
          # https://www.kkaneko.jp/data/bigdata/andktools.html
          
          cd binutils-${binutils_version}
          mkdir arm-linux-androideabi
          cd arm-linux-androideabi
          ../configure --prefix=/tmp/prefix --host=x86_64-pc-linux-gnu --with-cross-host=x86_64-pc-linux-gnu --target=arm-linux-androideabi \
            --build=x86_64-pc-linux-gnu \
            --enable-gnu-as --enable-gnu-ld --enable-multilib --enable-generated-files-in-srcdir --enable-version-specific-runtime-libs \
            --disable-werror --enable-libtool --disable-nls --disable-shared \
            --disable-threads --disable-clocale \
            --with-sysroot=${ANDROID_NDK_HOME}/toolchains/llvm/prebuilt/linux-x86_64/sysroot
          make -j$(nproc)
          make install
          
      - name: clone2
        run: |
          wget -nv https://ftp.gnu.org/gnu/gcc/gcc-${gcc_version}/gcc-${gcc_version}.tar.xz
          tar xf gcc-${gcc_version}.tar.xz
                    
      - name: build2
        run: |
          # https://www.kkaneko.jp/data/bigdata/andktools.html
          
          cd gcc-${gcc_version}
          mkdir arm-linux-androideabi
          cd arm-linux-androideabi
          CFLAGS="-I/usr/include/x86_64-linux-gnu" \
          ../configure --prefix=/tmp/prefix --host=x86_64-pc-linux-gnu --with-cross-host=x86_64-pc-linux-gnu --target=arm-linux-androideabi \
            --enable-languages=c,c++,fortran --disable-lto \
            --build=x86_64-pc-linux-gnu \
            --enable-gnu-as --enable-gnu-ld --enable-multilib --enable-generated-files-in-srcdir --enable-version-specific-runtime-libs \
            --disable-werror --enable-libtool --disable-nls --disable-shared \
            --disable-threads --disable-clocale \
            --enable-interwork \
            --enable-multiarch \
            --with-arch=armv7-a --with-float=soft --with-float-abi=softfp --with-fpu=vfp \
            --without-newlib --without-headers \
            --disable-libstdcxx --disable-hosted-libstdcxx --disable-libstdcxx-threads \
            --disable-werror \
            --disable-checking \
            --disable-ppl-version-check --disable-cloog-version-check \
            --disable-libssp --disable-libmudflap --disable-libgomp --disable-sjlj-exceptions --disable-tls --disable-libitm --disable-libatomic \
            --disable-bootstrap \
            --with-sysroot=${ANDROID_NDK_HOME}/toolchains/llvm/prebuilt/linux-x86_64/sysroot
          make -j$(nproc)
          make install
                    
      - name: archive
        run: |
          7z a build.7z /tmp/prefix
          
      - name: store
        uses: actions/upload-artifact@v3
        with:
          name: android-ndk-gfortran
          path: build.7z
          
