name: avd-termux

on:
    push:
      branches: [ main ]
      paths:
        - '.github/workflows/avd-termux.yml'
    workflow_dispatch:
 
jobs:
  build:
    runs-on: macos-12
  
    steps:
      - uses: actions/checkout@v3
          
      - name: download termux
        run: |
          wget -nc -nv https://github.com/termux/termux-app/releases/download/v0.118.0/termux-app_v0.118.0+github-debug_x86.apk -O termux.apk

      - name: setup avd
        run: |
          source ${HOME}/.bashrc
          
          ${ANDROID_HOME}/tools/bin/sdkmanager 'system-images;android-29;default;x86'
          echo no | ${ANDROID_HOME}/tools/bin/avdmanager create avd --force --name testAVD --package 'system-images;android-29;default;x86'

      - name: main
        run: |
          ${ANDROID_HOME}/emulator/emulator -avd testAVD &>avd.log &
          sleep 1m
          ps aux | grep emulator
          ${ANDROID_HOME}/platform-tools/adb devices
          ${ANDROID_HOME}/platform-tools/adb install termux.apk
          
          # start app
          adb shell am start -n com.termux/com.termux.app.TermuxActivity
          sleep 1m

      - name: cat log
        if: always()
        run: |
          cat avd.log
          
      - name: Store built file
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build.tar
          
