name: avd-termux

on:
    push:
      branches: [ main ]
      paths:
        - '.github/workflows/avd-termux.yml'
    workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v3

      - name: download termux
        run: |
          wget -nc -nv https://github.com/termux/termux-app/releases/download/v0.118.0/termux-app_v0.118.0+github-debug_x86.apk

      - name: setup avd
        run: |
          ${ANDROID_HOME}/tools/bin/sdkmanager 'system-images;android-29;default;x86'

      - name: main
        run: |
          ${ANDROID_HOME}/emulator/emulator -avd testAVD &>/dev/null &
          sleep 1m
          ${ANDROID_HOME}/platform-tools/adb devices

      - name: Store built file
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build.tar
          
