name: build-apk

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/build-apk.yml'
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-22.04
  
    steps:
      - name: clone
        run: |
          git clone https://github.com/termux/termux-gui.git .
          
      - name: build
        run: |
          ./gradlew assembleRelease

      - name: archive
        run: |
          tar xf build.tar $( find -name '*.apk' )
          
      - name: store
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: build.tar
