name: build_wine_android

on:
    push:
      branches: [ main ]
      paths:
        - '.github/workflows/build_wine_android.yml'
    workflow_dispatch:

env:
  wine_version: '7.10'
  android_api: '26'
  android_ndk: 'android-ndk-r21d'
  llvm_mingw: 'llvm-mingw-20201020-ucrt-ubuntu-18.04'
  gradle: 'gradle-3.5.1'
  freetype: 'freetype-2.10.4'
  gmp: 'gmp-6.2.1'
  nettle: 'nettle-3.6'
  gnutls: 'gnutls-3.7.0'
  openldap: 'openldap-2.4.56'
  cups: 'cups-2.3.3'
  gecko: 'wine-gecko-2.47.2'
  host: 'aarch64-linux-android'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: prepare
        run: |
          echo "pwd: ${PWD}"
          echo -n "bzip2: " ; which -a bzip2
          mkdir ${HOME}/src ${HOME}/build

      - name: prepare android ndk
        run: |
          mkdir tmp ; cd tmp
          wget -nv https://dl.google.com/android/repository/${{ env.android_ndk }}-linux-x86_64.zip -O android_ndk.zip
          unzip -q android_ndk.zip
          mv ${{ env.android_ndk }} ${HOME}
          # echo "CC=${HOME}/${{ env.android_ndk }}/toolchains/llvm/prebuilt/linux-x86_64/bin/${{ env.host }}${{ env.android_api }}-clang" >> $GITHUB_ENV
          cd .. ; rm -r tmp

      - name: prepare llvm mingw
        run: |
          mkdir tmp ; cd tmp
          wget -nv https://github.com/mstorsjo/llvm-mingw/releases/download/20201020/${{ env.llvm_mingw }}.tar.xz -O llvm-mingw.tar.xz
          tar xf llvm-mingw.tar.xz
          mv ${{ env.llvm_mingw }} ${HOME}
          # echo "llvm_mingw_path=${HOME}/${{ env.llvm_mingw }}/bin" >> $GITHUB_ENV
          cd .. ; rm -r tmp

      - name: clone wine source
        run: |
          mkdir tmp ; cd tmp
          wget -nv https://github.com/wine-mirror/wine/archive/refs/tags/wine-${{ env.wine_version }}.tar.gz -O wine.tar.xz
          tar xf wine.tar.xz
          mv wine-wine-${{ env.wine_version }} ${HOME}/src/wine
          cd .. ; rm -r tmp

      - name: prepare wine tools
        run: |
          mkdir ${HOME}/wine-tools ; cd ${HOME}/wine-tools
          ${HOME}/src/wine/configure --without-x --enable-win64
          make -j2 __tooldeps__

      - name: set env
        run: |
          echo "CC=${HOME}/${{ env.android_ndk }}/toolchains/llvm/prebuilt/linux-x86_64/bin/${{ env.host }}${{ env.android_api }}-clang" >> $GITHUB_ENV
          echo "PATH=${HOME}/${{ env.llvm_mingw }}/bin:${PATH}" >> $GITHUB_ENV
          echo "CFLAGS=${CFLAGS} -I${HOME}/build/include" >> $GITHUB_ENV
          echo "LDFLAGS=${LDFLAGS} -L${HOME}/build/lib" >> $GITHUB_ENV

      - name: clone freetype source
        run: |
          mkdir tmp ; cd tmp
          wget -nv http://download.savannah.gnu.org/releases/freetype/${{ env.freetype }}.tar.xz -O freetype.tar.xz
          tar xf freetype.tar.xz
          mv ${{ env.freetype }} ${HOME}/src/freetype
          cd .. ; rm -r tmp

      - name: build freetype
        run: |
          cd ${HOME}/src/freetype
          ./configure --prefix=${HOME}/build --host=${{ env.host }} --without-png
          make -j2
          make install

      - name: clone gmp source
        run: |
          mkdir tmp ; cd tmp
          wget -nv https://gmplib.org/download/gmp/${{ env.gmp }}.tar.xz -O gmp.tar.xz
          tar xf gmp.tar.xz
          mv ${{ env.gmp }} ${HOME}/src/gmp
          cd .. ; rm -r tmp

      - name: build gmp
        run: |
          cd ${HOME}/src/gmp
          ./configure --prefix=${HOME}/build --host=${{ env.host }} --disable-static
          make -j2
          make install

      - name: clone nettle source
        run: |
          mkdir tmp ; cd tmp
          wget -nv https://ftp.gnu.org/gnu/nettle/${{ env.nettle }}.tar.gz -O nettle.tar.gz
          tar xf nettle.tar.gz
          mv ${{ env.nettle }} ${HOME}/src/nettle
          cd .. ; rm -r tmp

      - name: build nettle
        run: |
          cd ${HOME}/src/nettle
          ./configure --prefix=${HOME}/build --host=${{ env.host }} --disable-shared --disable-documentation
          make -j2
          make install

      - name: clone gnutls source
        run: |
          mkdir tmp ; cd tmp
          version=v$(expr ${{ env.gnutls }} : '.*-\([0-9]\+\.[0-9]\+\)')
          wget -nv https://www.gnupg.org/ftp/gcrypt/gnutls/${version}/${{ env.gnutls }}.tar.xz -O gnutls.tar.xz
          tar xf gnutls.tar.xz
          mv ${{ env.gnutls }} ${HOME}/src/gnutls
          cd .. ; rm -r tmp

      - name: build gnutls
        run: |
          cd ${HOME}/src/gnutls
          ./configure --prefix=${HOME}/build --host=${{ env.host }} --without-p11-kit --without-idn --with-included-libtasn1 --with-included-unistring -disable-cxx \
            --disable-maintainer-mode --disable-static --disable-doc --disable-tools --disable-tests \
            PKG_CONFIG=true \
            LIBS="-lgmp -lnettle -lhogweed.a"
          make -j2
          make install

      - name: clone openldap source
        run: |
          mkdir tmp ; cd tmp
          wget -nv ftp://ftp.openldap.org/pub/OpenLDAP/openldap-release/${{ env.openldap }}.tgz -O openldap.tgz
          tar xf openldap.tgz
          mv ${{ env.openldap }} ${HOME}/src/openldap
          cd .. ; rm -r tmp

      - name: build openldap
        run: |
          cp ${HOME}/src/gnutls/build-aux/ltmain.sh ${HOME}/src/gnutls/build-aux/config.guess ${HOME}/src/gnutls/build-aux/config.sub ${HOME}/src/openldap/build
          cd ${HOME}/src/openldap
          aclocal && autoconf

          cd ${HOME}/src/openldap
          ./configure --prefix=${HOME}/build --host=${{ env.host }} --with-yielding_select=yes --disable-bdb --disable-hdb ac_cv_func_memcmp_working=yes CPPFLAGS=-DANDROID
          make -j2
          make install

      - name: build wine
        run: |
          cd ${HOME}/src/wine
          ${HOME}/src/wine/configure --prefix=${HOME}/build --host=${{ env.host }} --with-wine-tools=${HOME}/wine-tools \
            LIBS="-lfreetype -lgnutls -lgmp -lldap_r-2.4 -llber-2.4"
          make -j2
          make install

      - name: strip built files
        if: always()
        run: |
          find ${HOME}/build -type f | xargs file | awk -F: '$2 ~ /not strip/ { print $1 }' | xargs ${HOME}/${{ env.android_ndk }}/toolchains/llvm/prebuilt/linux-x86_64/bin/${{ env.host }}-strip --strip-all --verbose

      - name: archive build files
        if: always()
        run: |
          7z a -mx=9 build.7z ${HOME}/build
          
      - name: Store built file
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build.7z

      - name: archive log files
        if: always()
        run: |
          mkdir ${HOME}/logs
          shopt -s globstar
          cp -a ${HOME}/**/*.log ${HOME}/logs || true
          7z a -mx=9 logs.7z ${HOME}/logs

      - name: Store log file
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: log
          path: logs.7z
