name: build-aosp

on:
    push:
      branches: [ main ]
      paths:
        - '.github/workflows/build-aosp.yml'
    workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      aosp_version: android-12.1.0_r27
      aosp_target: aosp_arm64-eng
  
    steps:
      - name: free space
        run: |
            sudo rm -rf \
                /usr/local \
                /usr/local/lib/node_modules \
                /usr/local/lib/heroku \
                /usr/local/.ghcup \
                /usr/local/share/powershell \
                /usr/local/share/chromium \
                /usr/share/dotnet \
                /usr/share/swift \
                /usr/share/miniconda \
                /usr/lib/jvm \
                /usr/lib/google-cloud-sdk \
                /usr/lib/mono \
                /usr/lib/firefox \
                /opt \
                /var/lib/docker \
                /home/{runner,runneradmin}/.{rustup,cargo,dotnet} \
                /home/linuxbrew \
                /etc/skel
                
      - name: get storage info
        run: |
            free -h
            df -h

      - name: get requirements
        run: |
          sudo apt -y install curl make zip unzip \
            git python default-jre openjdk-8-jdk \
            bison g++-multilib gcc-multilib libxml2-utils

          curl https://storage.googleapis.com/git-repo-downloads/repo | sudo tee /bin/repo
          sudo chmod +x /bin/repo
          
      - name: clone
        run: |
          repo init -u https://android.googlesource.com/platform/manifest -b ${aosp_version} --depth=1
          repo sync -c -j8
          
      - name: build
        run: |
          export LC_ALL=C
          source build/envsetup.sh
          lunch ${aosp_target}
          make -j$(nproc)
          
      - name: archive built files
        run: |
          XZ_OPT=-e9 tar -Jcf ${{ env.aosp_version }}_${{ env.aosp_target }}.tar.xz out
          
      - name: Store built file
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.aosp_version }}_${{ env.aosp_target }}
          path: |
            ${{ env.aosp_version }}_${{ env.aosp_target }}.tar.xz
