name: build-onnxruntime-android

on:
  push:
    branches: [ main ]
    paths:
      - ".github/workflows/build-onnxruntime-android.yml"
  workflow_dispatch:

env:
  ONNX_VERSION: "1.14.1"
  ARCH: "aarch64"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get source code
        run: |
          git clone --depth=1 --recurse-submodules --branch=v${ONNX_VERSION} https://github.com/microsoft/onnxruntime ${GITHUB_WORKSPACE}/src
      - uses: actions/cache@v3
        id: cache-protoc
        with:
          path: ${{ github.workspace }}/host-protoc
          key: onnx_protoc_${{ env.ONNX_VERSION }}
      - uses: seanmiddleditch/gha-setup-ninja@master
      - if: ${{ steps.cache-protoc.outputs.cache-hit != 'true' }}
        name: Build Host Protoc
        run: |
          mkdir ${GITHUB_WORKSPACE}/host-{protoc,build}
          cd ${GITHUB_WORKSPACE}/host-build
          cmake -GNinja \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_INSTALL_PREFIX=${GITHUB_WORKSPACE}/host-protoc \
            -Dprotobuf_BUILD_TESTS=OFF \
            -Dprotobuf_WITH_ZLIB_DEFAULT=OFF \
            -Dprotobuf_BUILD_SHARED_LIBS=OFF \
            ${GITHUB_WORKSPACE}/src/cmake/external/protobuf/cmake
          ninja
          ninja install
