name: wine

on:
    push:
      branches: [ main ]
      paths:
        - 'wine/**'
        - '.github/workflows/build-wine.yml'
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v3

      - name: Run a multi-line script
        run: |
          sudo apt-get -qq purge -y --auto-remove man-db
          sudo dpkg --add-architecture i386
          sudo apt-get -qq update
          sudo apt-get -qq install -y gcc-mingw-w64 libasound2-dev libpulse-dev libdbus-1-dev libfontconfig-dev libfreetype-dev libgnutls28-dev libjpeg62-turbo-dev libpng-dev libtiff-dev libgl-dev libunwind-dev libxml2-dev libxslt1-dev libfaudio-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libmpg123-dev libosmesa6-dev libsdl2-dev libudev-dev libvkd3d-dev libvulkan-dev libcapi20-dev liblcms2-dev libcups2-dev libgphoto2-dev libsane-dev libgsm1-dev libkrb5-dev libldap2-dev samba-dev ocl-icd-opencl-dev libpcap-dev libusb-1.0-0-dev libv4l-dev
          wget -nc -nv https://github.com/wine-mirror/wine/archive/refs/tags/wine-7.10.tar.gz
          tar xf wine-7.10.tar.gz --strip-components 1
          mkdir build && cd build
          ../configure
          make
          cd ..
          tar -Jcf wine-7.10-amd64-build.tar.xz build
      - name: Store built files
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: wine-7.10-amd64-build.tar.xz
