name: buildroot

on:
    push:
      branches: [ main ]
      paths:
        - '.github/workflows/buildroot.yml'
    workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-18.04
    name: Build on native aarch64
  
    steps:
      - uses: actions/checkout@v3

      - uses: uraimo/run-on-arch-action@v2
        id: aarch64-build-on-qemu-aarch64
        with:
          architecture: aarch64
          distribution: ubuntu18.04
          run: |
            apt-get update
            apt-get install -y cmake gcc g++
            pwd > built
          
            # find ${HOME}/wine-build -type f | xargs file | awk -F: '$2 ~ /not stripped/ {print $1}' | xargs strip --strip-all --verbose
                    
      - name: built file info
        run: |
          file built
          sha256sum built
      - name: Store built file
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: built-artifact
          path: built
