name: clone

on:
    push:
      branches: [ main ]
      paths:
        - '.github/workflows/clone.yml'
    workflow_dispatch:
    
env:
  name: "wine"
  git: "https://github.com/wine-mirror/wine.git"
  version: "wine-7.10"
 
jobs:
  build:
    runs-on: macos-latest
  
    steps:
      - name: install
        run: |
          brew install squashfs
      
      - name: clone
        run: |
          sudo git clone --recursive --depth=1 --branch=${{ env.version }} ${{ env.git }} ./${{ env.name }}
          sudo rm -r ./${{ env.name }}/.git
          
      - name: archive
        run: |
          # sudo mksquashfs ${{ env.name }} ./${{ env.name }}-${{ env.version }}.squashfs -comp xz -Xdict-size 100%
          sudo XZ_OPT=-e9 tar cJf ./${{ env.name }}-${{ env.version }}.tar.xz ${{ env.name }}
          
      - name: store
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.name }}-${{ env.version }}
          path: ./${{ env.name }}-${{ env.version }}.tar.xz
