name: android-pytorch

on:
    push:
      branches: [ main ]
      paths:
        - '.github/workflows/android-pytorch.yml'
    workflow_dispatch:
    
env:
  name: "pytorch"
  git: "https://github.com/pytorch/pytorch.git"
  version: "v1.11.0"
 
jobs:
  build:
    runs-on: macos-latest
  
    steps:
      - name: install
        run: |
          brew install squashfs
      
      - name: clone
        run: |
          sudo git clone --recursive -b ${{ env.version }} ${{ env.git }} ./${{ env.name }}
          
      - name: archive
        run: |
          sudo mksquashfs ./${{ env.name }} ${{ env.name }}-${{ env.version }}.squashfs -comp xz -Xdict-size 100%
          
      - name: store
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.name }}-${{ env.version }}
          path: ${{ env.name }}-${{ env.version }}.squashfs
