name: compile-jetson-2g-4

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/compile-jetson-2g-4.yml'
      - 'compile-jetson-2g/**'
  workflow_dispatch:

jobs:
  build1:
      uses: ./.github/workflows/compile-jetson-2g-steps.yml
      with:
        cache1: 12_9a264617081213d7ce02b53eac1b7e0f81783cbb
        cache2: 1_${{ github.sha }}
        
  build2:
      uses: ./.github/workflows/compile-jetson-2g-steps.yml
      needs: build1
      with:
        cache1: 1_${{ github.sha }}
        cache2: 2_${{ github.sha }}
        
  build3:
      uses: ./.github/workflows/compile-jetson-2g-steps.yml
      needs: build2
      with:
        cache1: 2_${{ github.sha }}
        cache2: 3_${{ github.sha }}
        
  build4:
      uses: ./.github/workflows/compile-jetson-2g-steps.yml
      needs: build3
      with:
        cache1: 3_${{ github.sha }}
        cache2: 4_${{ github.sha }}
        
  build5:
      uses: ./.github/workflows/compile-jetson-2g-steps.yml
      needs: build4
      with:
        cache1: 4_${{ github.sha }}
        cache2: 5_${{ github.sha }}
        
  build6:
      uses: ./.github/workflows/compile-jetson-2g-steps.yml
      needs: build5
      with:
        cache1: 5_${{ github.sha }}
        cache2: 6_${{ github.sha }}
        
  build7:
      uses: ./.github/workflows/compile-jetson-2g-steps.yml
      needs: build6
      with:
        cache1: 6_${{ github.sha }}
        cache2: 7_${{ github.sha }}
        
  build8:
      uses: ./.github/workflows/compile-jetson-2g-steps.yml
      needs: build7
      with:
        cache1: 7_${{ github.sha }}
        cache2: 8_${{ github.sha }}
        
  build9:
      uses: ./.github/workflows/compile-jetson-2g-steps.yml
      needs: build8
      with:
        cache1: 8_${{ github.sha }}
        cache2: 9_${{ github.sha }}
        
  build10:
      uses: ./.github/workflows/compile-jetson-2g-steps.yml
      needs: build9
      with:
        cache1: 9_${{ github.sha }}
        cache2: 10_${{ github.sha }}
        
  build11:
      uses: ./.github/workflows/compile-jetson-2g-steps.yml
      needs: build10
      with:
        cache1: 10_${{ github.sha }}
        cache2: 11_${{ github.sha }}
        
  build12:
      uses: ./.github/workflows/compile-jetson-2g-steps.yml
      needs: build11
      with:
        cache1: 11_${{ github.sha }}
        cache2: 12_${{ github.sha }}
        
  build13:
      uses: ./.github/workflows/compile-jetson-2g-steps.yml
      needs: build12
      with:
        cache1: 12_${{ github.sha }}
        cache2: 13_${{ github.sha }}
        
  build14:
      uses: ./.github/workflows/compile-jetson-2g-steps.yml
      needs: build13
      with:
        cache1: 13_${{ github.sha }}
        cache2: 14_${{ github.sha }}
        
  build15:
      uses: ./.github/workflows/compile-jetson-2g-steps.yml
      needs: build14
      with:
        cache1: 14_${{ github.sha }}
        cache2: 15_${{ github.sha }}
        
  build16:
      uses: ./.github/workflows/compile-jetson-2g-steps.yml
      needs: build15
      with:
        cache1: 15_${{ github.sha }}
        cache2: 16_${{ github.sha }}
        
  build17:
      uses: ./.github/workflows/compile-jetson-2g-steps.yml
      needs: build16
      with:
        cache1: 16_${{ github.sha }}
        cache2: 17_${{ github.sha }}
        
  build18:
      uses: ./.github/workflows/compile-jetson-2g-steps.yml
      needs: build17
      with:
        cache1: 17_${{ github.sha }}
        cache2: 18_${{ github.sha }}
        
  build19:
      uses: ./.github/workflows/compile-jetson-2g-steps.yml
      needs: build18
      with:
        cache1: 18_${{ github.sha }}
        cache2: 19_${{ github.sha }}
        
  build20:
      uses: ./.github/workflows/compile-jetson-2g-steps.yml
      needs: build19
      with:
        cache1: 19_${{ github.sha }}
        cache2: 20_${{ github.sha }}
        
