name: compile-jetson-2g-4

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/compile-jetson-2g-4.yml'
      - 'compile-jetson-2g/**'
  workflow_dispatch:

jobs:
  build1:
      uses: ./.github/actions/compile-jetson-2g-steps.yml@main
      with:
        cache1: 1_929c4dd2c2ffda560c0dcd8f20edb23e646f44ce
        cache2: 1_${{ github.sha }}
        
  build2:
      uses: ./.github/actions/compile-jetson-2g-steps.yml@main
      with:
        cache1: 1_${{ github.sha }}
        cache2: 2_${{ github.sha }}
        
