name: buildroot

on:
    push:
      branches: [ main ]
      paths:
        - '.github/workflows/mmdebstrap.yml'
    workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-22.04
    name: Build on native aarch64
  
    steps:
      - uses: actions/checkout@v3
      
      - name: info
        run: |
            pwd
            df -h
            
      - name: install mmdebstrap
        run: |
            sudo apt-get update
            sudo apt-get install -y --no-install-recommends mmdebstrap arch-test
            
      - uses: dbhi/qus/action@main
          
      - name: link qemu static
        run: |
          for i in /qus/bin/qemu-*-static ; do
            sudo ln -s ${i} ${i///qus}
          done
        
      - name: install mmdebstrap
        run: |
            echo apt:\  ;  which -a apt
            rootfs="rootfs"
            dest="bullseye"
            keys="648ACFD622F3D138 0E98404D386FA1D9"
            for key in ${keys} ; do sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys ${key} ; done
            sudo mmdebstrap --components=main,contrib,non-free --include=python3-numpy \
                --variant=apt --architecture=arm64 \
                --dpkgopt='path-exclude=/usr/share/man/*' \
                --dpkgopt='path-exclude=/usr/share/locale/*/LC_MESSAGES/*.mo' \
                --dpkgopt='path-exclude=/usr/share/locale/*' \
                --dpkgopt='path-exclude=/usr/share/doc/*' \
                --dpkgopt='path-exclude=/etc/cron.d/*' \
                --dpkgopt='path-exclude=/etc/cron.daily/*' \
                --dpkgopt='path-exclude=/etc/cron.hourly/*' \
                --dpkgopt='path-exclude=/etc/cron.monthly/*' \
                --dpkgopt='path-exclude=/etc/cron.weekly/*' \
                 ${dest} ${rootfs} https://deb.debian.org/debian/
            # find ${HOME}/wine-build -type f | xargs file | awk -F: '$2 ~ /not stripped/ {print $1}' | xargs strip --strip-all --verbose
            sudo tar Jcf rootfs.tar.xz ${rootfs}

      - name: built file info
        run: |
          file rootfs.tar.xz
          sha256sum rootfs.tar.xz
      - name: Store built file
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: built-artifact
          path: rootfs.tar.xz
