name: mmdebstrap-jetson-2g

on:
    push:
      branches: [ main ]
      paths:
        - '.github/workflows/mmdebstrap-jetson-2g.yml'
    workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-22.04
    name: Build on native aarch64
  
    steps:
      - uses: actions/checkout@v3
      
      - name: Download base image
        run: |
            wget -nv https://developer.nvidia.com/embedded/l4t/r32_release_v7.1/jp_4.6.1_b110_sd_card/jetson_nano_2gb/jetson-nano-2gb-jp461-sd-card-image.zip \
              -O image.zip
            
      - name: Extract base image
        run: |
            unzip image.zip  # extracts "sd-blob.img"
            
      - name: Install mmdebstrap
        run: |
            sudo apt-get update
            sudo apt-get install -y --no-install-recommends mmdebstrap arch-test qemu-user-static qemu-utils
            sudo modprobe nbd max_part=63
            
            sudo qemu-nbd -c /dev/nbd0 --format=raw sd-blob.img
            mkdir nbd0p1 rootfs
            sudo mount /dev/nbd0p1 -t ext4 -o noatime,nobarrier nbd0p1
                    
      - name: Create rootfs
        run: |
            echo ok > rootfs/test.txt
            exit 0
        
            echo apt:\  ;  which -a apt
            rootfs="rootfs"
            dest="bullseye"
            keys="648ACFD622F3D138 0E98404D386FA1D9"
            for key in ${keys} ; do sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys ${key} ; done
            sudo mmdebstrap --components=main,contrib,non-free --include=python3-numpy,libsndfile1 \
                --variant=apt --architecture=arm64 \
                --dpkgopt='path-exclude=/usr/share/man/*' \
                --dpkgopt='path-exclude=/usr/share/locale/*/LC_MESSAGES/*.mo' \
                --dpkgopt='path-exclude=/usr/share/locale/*' \
                --dpkgopt='path-exclude=/usr/share/doc/*' \
                --dpkgopt='path-exclude=/etc/cron.d/*' \
                --dpkgopt='path-exclude=/etc/cron.daily/*' \
                --dpkgopt='path-exclude=/etc/cron.hourly/*' \
                --dpkgopt='path-exclude=/etc/cron.monthly/*' \
                --dpkgopt='path-exclude=/etc/cron.weekly/*' \
                 ${dest} ${rootfs} https://deb.debian.org/debian/
            cd ${rootfs}
            sudo rm -rf var/cache/* var/log/*
            echo -n '' | sudo tee etc/motd >/dev/null
            echo 'nameserver 8.8.8.8' | sudo tee etc/resolv.conf >/dev/null
            cd ..
            # find ${HOME}/wine-build -type f | xargs file | awk -F: '$2 ~ /not stripped/ {print $1}' | xargs strip --strip-all --verbose
            sudo tar Jcf rootfs.tar.xz ${rootfs}
            
      - name: Disk modify
        run: |
            sudo umount nbd0p1
            sudo qemu-nbd --disconnect /dev/nbd0 
            sudo killall --wait qemu-nbd || true
        
            dir_size_gb=`du --summarize rootfs | awk '{print int($1/1024/1024/1024)+1}'`
            echo "dir_size_gb=${dir_size_gb}"
            
            sgdisk --delete=1 sd-blob.img
            truncate -s ${dir_size_gb}G sd-blob.img
            echo -e "w\ny" | gdisk sd-blob.img
            sgdisk --new=1:: sd-blob.img
            echo 'name 1 APP' | parted sd-blob.img
            sgdisk --print sd-blob.img
            
            sudo qemu-nbd -c /dev/nbd0 --format=raw sd-blob.img
            sudo mkfs.ext4 -O ^has_journal,^64bit,^metadata_csum -E root_owner=0:0 -m 0 /dev/nbd0p1
            sudo mount /dev/nbd0p1 -t ext4 -o noatime,nobarrier nbd0p1
            df -h ./nbd0p1
            
            sudo cp -a rootfs/. nbd0p1
            
            sudo umount nbd0p1
            sudo qemu-nbd --disconnect /dev/nbd0 
            sudo killall --wait qemu-nbd || true
            
            echo archiving built file
            7z a rootfs.tar.xz sd-blob.img

      - name: built file info
        run: |
          file rootfs.tar.xz
          sha256sum rootfs.tar.xz
      - name: Store built file
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: built-artifact
          path: rootfs.tar.xz
