name: buildroot

on:
    push:
      branches: [ main ]
      paths:
        - '.github/workflows/mmdebstrap.yml'
    workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-20.04
    name: Build on native aarch64
  
    steps:
      - uses: actions/checkout@v3
      
      - name: download buildroot
        run: |
          pwd
          mkdir -p buildroot
          cd buildroot
      - uses: uraimo/run-on-arch-action@v2
        id: aarch64-build-on-qemu-aarch64
        with:
          arch: aarch64
          distro: ubuntu20.04
          run: |
            pwd
            cd buildroot
            make qemu_aarch64_virt_defconfig
            make BR2_JLEVEL=`getconf _NPROCESSORS_ONLN`
            ls -lha
            # find ${HOME}/wine-build -type f | xargs file | awk -F: '$2 ~ /not stripped/ {print $1}' | xargs strip --strip-all --verbose
                    
      - name: built file info
        run: |
          file built
          sha256sum built
      - name: Store built file
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: built-artifact
          path: built
