name: mmdebstrap-jetson-2g

on:
    push:
      branches: [ main ]
      paths:
        - '.github/workflows/mmdebstrap-jetson-2g.yml'
    workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-22.04
    name: Build on native aarch64
  
    steps:
      - uses: actions/checkout@v3
      
      - name: Download base image
        run: |
            wget -nv https://developer.nvidia.com/embedded/l4t/r32_release_v7.1/jp_4.6.1_b110_sd_card/jetson_nano_2gb/jetson-nano-2gb-jp461-sd-card-image.zip \
              -O image.zip
            
      - name: Extract base image
        run: |
            unzip image.zip  # extracts "sd-blob.img"
            
      - name: Install mmdebstrap
        run: |
            sudo apt-get update
            sudo apt-get install -y --no-install-recommends mmdebstrap arch-test qemu-user-static qemu-utils
            sudo modprobe nbd max_part=63
            
            sudo qemu-nbd -c /dev/nbd0 --format=raw sd-blob.img
            mkdir nbd0p1 rootfs
            sudo mount /dev/nbd0p1 -t ext4 -o noatime,nobarrier nbd0p1
                    
      - name: Create rootfs
        run: |
            sudo mmdebstrap --components="main restricted universe multiverse" focal /mnt  \
                --variant=apt --architecture=arm64 \
                --include="xfce4" \
                --dpkgopt='path-exclude=/usr/share/man/*' \
                --dpkgopt='path-exclude=/usr/share/doc/*' \
                --dpkgopt='path-exclude=/usr/share/locale/*' \
                --dpkgopt='path-include=/usr/share/locale/en/*' \
                --dpkgopt='path-include=/usr/share/locale/ja/*' \
                --dpkgopt='path-exclude=/etc/cron.d/*' \
                --dpkgopt='path-exclude=/etc/cron.daily/*' \
                --dpkgopt='path-exclude=/etc/cron.hourly/*' \
                --dpkgopt='path-exclude=/etc/cron.monthly/*' \
                --dpkgopt='path-exclude=/etc/cron.weekly/*' \
                 jammy rootfs http://ports.ubuntu.com/ubuntu-ports
                 
            sudo cp -a nbd0p1/etc/nv_boot_control.conf rootfs/etc/
            sudo cp -a nbd0p1/etc/apt/sources.list.d/nvidia-l4t-apt-source.list rootfs/etc/apt/sources.list.d/
            sudo cp -a nbd0p1/boot/extlinux /mnt/boot/
  
            echo "deb http://ports.ubuntu.com/ubuntu-ports jammy main restricted universe multiverse" | sudo tee rootfs/etc/apt/sources.list >/dev/null
            echo "/dev/root / ext4 defaults,noatime,nobarrier,commit=60 0 1" | sudo tee rootfs/etc/fstab >/dev/null
            echo "jetson-nano-2g" | sudo tee rootfs/etc/hostname >/dev/null            
            echo "Asia/Tokyo" | sudo tee rootfs/etc/timezone >/dev/null
            
      - name: Disk modify
        run: |
            sudo umount nbd0p1
            sudo qemu-nbd --disconnect /dev/nbd0 
            sudo killall --wait qemu-nbd || true
        
            dir_size_mb=`du --summarize rootfs | awk '{print int($1/1024/1024)+100}'`
            echo "dir_size_mb=${dir_size_mb}"
            
            sgdisk --delete=1 sd-blob.img
            truncate -s ${dir_size_mb}M sd-blob.img
            echo -e "w\ny" | gdisk sd-blob.img
            sgdisk --new=1:: sd-blob.img
            echo 'name 1 APP' | parted sd-blob.img
            sgdisk --print sd-blob.img
            
            sudo qemu-nbd -c /dev/nbd0 --format=raw sd-blob.img
            sudo mkfs.ext4 -O ^has_journal,^64bit,^metadata_csum -E root_owner=0:0 -m 0 /dev/nbd0p1
            sudo mount /dev/nbd0p1 -t ext4 -o noatime,nobarrier nbd0p1
            df -h ./nbd0p1
            
            sudo cp -a rootfs/. nbd0p1
            
            sudo umount nbd0p1
            sudo qemu-nbd --disconnect /dev/nbd0 
            sudo killall --wait qemu-nbd || true
            
            echo archiving built file
            7z a rootfs.tar.xz sd-blob.img

      - name: built file info
        run: |
          file rootfs.tar.xz
          sha256sum rootfs.tar.xz
      - name: Store built file
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: built-artifact
          path: rootfs.tar.xz
