name: qemu

on:
    push:
      branches: [ main ]
      paths:
        - 'qemu/**'
        - '.github/workflows/qemu.yml'
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
  
    steps:
      - uses: actions/checkout@v3

      - name: Run a multi-line script
        run: |
            bash qemu/build.sh
            python3 qemu/build.py
            7z a -mx=9 qemu.img.7z qemu.img

      - name: Store log files
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: img
          path: qemu.img.7z
