name: qemu_debian

on:
    push:
      branches: [ main ]
      paths:
        - 'qemu_debian/**'
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
  
    steps:
      - uses: actions/checkout@v3

      - name: get storage info
        run: |
            free -h
            df -h
            
      - name: Run a multi-line script
        run: |
            echo "path-exclude=/usr/share/man/*" | sudo tee /etc/dpkg/dpkg.cfg.d/01_nodoc
            sudo apt-get install -y --no-install-recommends qemu-system-x86 qemu-utils libguestfs-tools
            # wget -nc -nv https://github.com/kawanakaiku/test-ci/releases/download/files/edk2-x86_64-code.fd
            # wget -nc -nv https://github.com/kawanakaiku/test-ci/releases/download/archlinux/archlinux-2022.06.01-x86_64.iso
            qemu-img create -f qcow2 qemu_debian.img 32G
            # python3 qemu_arch/build.py
            # sudo virt-sparsify qemu_debian.img --convert qcow2 qemu_debian2.img && mv qemu_debian2.img qemu_debian.img
            sudo modprobe nbd max_part=63
            sudo qemu-nbd -c /dev/nbd0 qemu_debian.img
            lsblk
            7z a -mx=9 qemu_debian.img.7z qemu_debian.img
            
      - name: Store 7z files
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: debian_img
          path: qemu_debian.img.7z
