name: qemu

on:
    push:
      branches: [ main ]
      paths:
        - 'qemu/**'
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
  
    steps:
      - uses: actions/checkout@v3

      - name: Run a multi-line script
        run: |
          sudo apt-get install -y --no-install-recommends qemu-system-x86 qemu-utils
          qemu-system-x86_64 --version
          wget -nc https://github.com/kawanakaiku/test-ci/releases/download/files/edk2-x86_64-code.fd
          wget -nc https://dl-cdn.alpinelinux.org/alpine/v3.16/releases/x86_64/alpine-virt-3.16.0-x86_64.iso
          timeout 180 python3 qemu/build.py

      - name: Store log files
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: log
          path: log.txt
