name: qemu

on:
    push:
      branches: [ main ]
      paths:
        - 'qemu/**'
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
  
    steps:
      - uses: actions/checkout@v3

      - name: Run a multi-line script
        run: |
          sudo apt-get install -y --no-install-recommends qemu-system-x86 qemu-utils
          qemu-system-x86_64 --version
          timeout 180 python3 qemu/build.py
