name: qemu

on:
    push:
      branches: [ main ]
      paths:
        - 'test/**'
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
  
    steps:
      - uses: actions/checkout@v3

      - name: Run a multi-line script
        run: |
          sudo apt-get install -y --no-install-recommends qemu-system-x86 qemu-utils
          which qemu-system-x86_64 || true
          which qemu-img || true
          qemu-system-x86_64 --version || true
          find / -name 'edk2-x86_64-code.fd' 2>/dev/null || true
