name: qemu

on:
    push:
      branches: [ main ]
      paths:
        - 'qemu/**'
        - '.github/workflows/qemu.yml'
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
  
    steps:
      - uses: actions/checkout@v3

      - name: Run a multi-line script
        run: |
            sudo apt-get install -y --no-install-recommends qemu-system-x86 qemu-utils libguestfs-tools
            qemu-system-x86_64 --version
            wget -nc -nv https://github.com/kawanakaiku/test-ci/releases/download/files/edk2-x86_64-code.fd
            wget -nc -nv https://dl-cdn.alpinelinux.org/alpine/v3.16/releases/x86_64/alpine-virt-3.16.0-x86_64.iso
            qemu-img create -f qcow2 qemu.img 2G
            python3 qemu/build.py
            sudo virt-sparsify qemu.img --convert qcow2 qemu2.img && mv qemu2.img qemu.img
            7z a -mx=9 qemu.img.7z qemu.img

      - name: Store log files
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: img
          path: qemu.img.7z
