### Auto build Box86 and release its binary with Github Action
name: raspios-box86

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Box86 Repository"
        run: |
          git clone https://github.com/ptitSeb/box86.git .

      - name: "Environment preparation"
        run: |
          sudo apt-get update

          sudo apt-get -y install git cmake make python3
          sudo apt-get -y install gcc-arm-linux-gnueabihf
          echo "BOX86_COMPILER=arm-linux-gnueabihf-gcc" >> $GITHUB_ENV
          echo "BOX86_PLATFORM_MARCRO=-DRPI4ARM64=1" >> $GITHUB_ENV
          
          echo BOX86_BUILD_TYPE=Release >> $GITHUB_ENV
          echo BOX86_HAVE_TRACE=0 >> $GITHUB_ENV

      - name: "Display Build info"
        run: |
          echo "CMake Platform Macro: ${{ env.BOX86_PLATFORM_MARCRO }}"
          echo "CMake C Compiler: ${{ env.BOX86_COMPILER }}"
          echo "Build type: ${{ env.BOX86_BUILD_TYPE }}"
          echo "Trace Enabled: ${{ env.BOX86_HAVE_TRACE }}"

      - name: "Build Box86"
        run: |
          _CFLAGS=' -mlittle-endian -mabi=lp64 -march=armv8-a+crc -mtune=cortex-a72'
          export CFLAGS+="${_CFLAGS}"
          export CXXFLAGS+="${_CFLAGS}"
        
          mkdir build
          cd build
          cmake .. -DCMAKE_C_COMPILER=${{ env.BOX86_COMPILER }}\
                   ${{ env.BOX86_PLATFORM_MARCRO }}\
                   -DCMAKE_BUILD_TYPE=${{ env.BOX86_BUILD_TYPE }}\
                   -DHAVE_TRACE=${{ env.BOX86_HAVE_TRACE }}\
                   -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON
          make -j$(nproc) VERBOSE=1

      - name: "Upload Artifact"
        uses: actions/upload-artifact@v2
        with:
          name: box86-RPI4-Release
          path: build/box86


