name: src

on:
    push:
      branches: [ main ]
      paths:
        - '.github/workflows/src.yml'
    workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-22.04
  
    steps:
      - name: clone
        run: |
          git clone --depth=1 --recursive --branch=v1.12.1 https://github.com/pytorch/pytorch torch
          
      - name: archive
        run: |
          tar -c -I 'xz -9e -T0' -f torch.tar.xz torch
  
      - name: store
        uses: actions/upload-artifact@v3
        with:
          name: torch
          path: torch.tar.xz
