name: streamlink-nuitka

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/streamlink-nuitka.yml'

jobs:
  build:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v3

      - name: Run a build script
        run: |
          mkdir build
          python3.exe -m pip install -U nuitka ordered-set streamlink
          python3.exe -m nuitka --standalone --onefile --follow-imports C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\streamlink_cli\__main__.py
          cd ..
          7z.exe a -mx=9 built.7z build
          
      - name: Store built files
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: built
          path: built.7z
