on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: run iceccd
        run: |
          git clone https://github.com/termux/termux-packages.git

          bash termux-packages/scripts/run-docker.sh bash -c '

          # invoke-rc.d: policy-rc.d denied execution of start.
          echo -e '#!/bin/sh\nexit 0' | sudo tee /usr/sbin/policy-rc.d >/dev/null

          # install icecc
          sudo apt update
          sudo apt install -y icecc

          # start daemon
          iceccd -s ${{ secrets.MY_IP }}
          '
