name: termux-chroot-python

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/termux-chroot-python.yml'
  workflow_dispatch:
    
env:
  TERMUX_PREFIX: /data/data/com.termux/files/usr
  TERMUX_HOME: /data/data/com.termux/files/home
  PIP_DISABLE_PIP_VERSION_CHECK: 1
 
jobs:
  build:
    runs-on: ubuntu-22.04
  
    steps:
      - name: get termux
        run: |
          mkdir termux-root
          wget -nv https://github.com/kawanakaiku/test-ci/releases/download/chroot-termux/termux-aarch64.tar.xz
          tar xf termux-aarch64.tar.xz -C termux-root
          
      - name: apt
        run: |
          wget -nv http://security.ubuntu.com/ubuntu/pool/universe/q/qemu/qemu-user-static_6.2+dfsg-2ubuntu6.2_amd64.deb
          sudo apt-get install -y --no-install-recommends ./*.deb
          exit
          
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends qemu-user-static
          
      - name: chroot termux
        run: |
          cd termux-root
          mkdir -p proc dev dev/pts sys
          
          sudo mount -t proc proc proc
          sudo mount -t devtmpfs udev dev
          sudo mount -t devpts devpts dev/pts
          sudo mount -t sysfs sysfs sys
          
          sudo cp /usr/bin/qemu-arm-static data/data/com.termux/files/usr/bin
          
          # set host file
          mkdir -p system/etc
          for host in pypi.python.org files.pythonhosted.org pypi.org \
            github.com objects.githubusercontent.com \
            packages.termux.dev
          do
            echo $( nslookup $host | awk '/^Address: / { print $2; exit }' ) " $host" >> system/etc/hosts
          done
          
          # suppress linker: Warning: failed to find generated linker configuration from "/linkerconfig/ld.config.txt"
          mkdir -p linkerconfig
          touch linkerconfig/ld.config.txt
          
          TERMUX_USER=$( sudo chroot .  /system/bin/stat -c '%U' ${TERMUX_PREFIX}/bin/env )
          TERMUX_GROUP=$( sudo chroot .  /system/bin/stat -c '%G' ${TERMUX_PREFIX}/bin/env )
          
          sudo ls -lha data/data/com.termux/files/usr/bin/env
          sudo chroot . ${TERMUX_PREFIX}/bin/env PATH=${TERMUX_PREFIX}/bin ls -lha /data/data/com.termux/files/usr/bin/env
          
          cat <<SH > /tmp/chroot
          #!/usr/bin/sh
          exec sudo chroot ${PWD} \
            ${TERMUX_PREFIX}/bin/su ${TERMUX_USER} \
            ${TERMUX_PREFIX}/bin/env \
            PATH=${TERMUX_PREFIX}/bin \
            LD_LIBRARY_PATH=${TERMUX_PREFIX}/lib \
            HOME=${TERMUX_HOME} \
            PIP_DISABLE_PIP_VERSION_CHECK=1 \
            "\$@"
          SH
          chmod +x /tmp/chroot
          
          /tmp/chroot bash <<BASH
          apt update
          apt upgrade -y ccache libopenblas
          BASH
          
      - name: clone
        run: |
          mkdir termux-root/python
          cd termux-root/python
          mkdir torch
          wget -nv https://github.com/pytorch/pytorch/releases/download/v1.12.1/pytorch-v1.12.1.tar.gz
          tar xf pytorch-v1.12.1.tar.gz --strip-components=1 -C torch
          
          cd torch
          sed -i -e 's/**build_options,/**build_options | {i: j for i, j in [i.strip().split("=", 1) for i in os.getenv("cmake_args").split(os.linesep) if "=" in i]},/' tools/setup_helpers/cmake.py
          find . -name CMakeLists.txt -o -name '*.cmake' | \
            xargs -n 1 sed -i \
            -e 's/\([^A-Za-z0-9_]ANDROID\)\([^A-Za-z0-9_]\)/\1_NO_TERMUX\2/g' \
            -e 's/\([^A-Za-z0-9_]ANDROID\)$/\1_NO_TERMUX/g'
          
      - name: build
        run: |
          cd termux-root
          /tmp/chroot bash <<CHROOT
          cd /python
          python3 -m pip wheel -r <( grep -v -e numpy torch/requirements.txt ) pip wheel setuptools
          python3 -m pip install *.whl
          
          pushd torch
          export cmake_args="
          ANDROID_NO_TERMUX=0
          USE_VULKAN=0
          BUILD_TEST=0
          "
          BUILD_TEST=0　USE_VULKAN=0 \
            python3 setup.py bdist_wheel
          popd
          CHROOT
  
      - name: store
        uses: actions/upload-artifact@v3
        with:
          name: built
          path: |
            - termux-root/python/*.whl
            - termux-root/python/torch/dist
