on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: run iceccd
        run: |
          git clone https://github.com/termux/termux-packages.git
          bash termux-packages/scripts/run-docker.sh bash -c '
          sudo apt update
          sudo apt install -y icecc
          iceccd -s ${{ secrets.MY_IP }}
          '
