name: termux-wheel

on:
    push:
      branches: [ main ]
      paths:
        - '.github/workflows/termux-wheel.yml'
    workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-22.04
  
    steps:
      - uses: actions/checkout@v3
          
      - name: setup termux python
        run: |
          wget -nc -nv https://packages-cf.termux.org/apt/termux-main/pool/main/p/python/python_3.10.5_aarch64.deb
          wget -nc -nv https://packages-cf.termux.org/apt/termux-main/pool/main/liba/libandroid-support/libandroid-support_28-2_aarch64.deb
          for deb in *.deb ; do
            ar x ${deb} data.tar.xz
            sudo tar -xf data.tar.xz --no-overwrite-dir -C /
            rm data.tar.xz ${deb}
          done
      - name: add NDK to PATH
        run: |
          sudo ln -s ${ANDROID_NDK_LATEST_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android{24,}-clang
          sudo ln -s ${ANDROID_NDK_LATEST_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android{24,}-clang++
          
      - name: setup crossenv
        run: |
          export PATH="${ANDROID_NDK_LATEST_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin:${PATH}"

          python3.10 -m pip install crossenv
          python3.10 -m crossenv /data/data/com.termux/files/usr/bin/python3.10 venv
          
          . venv/bin/activate
          
          cross-pip install pip wheel setuptools
          build-pip install pip wheel setuptools
           
      - name: build
        run: |
          export PATH="${ANDROID_NDK_LATEST_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin:${PATH}"
          export LDFLAGS="-L/data/data/com.termux/files/usr/lib"
          
          . venv/bin/activate
          
          mkdir -p build
          cd build
          cross-pip wheel --no-binary :all: yt-dlp
                    
      - name: files
        run: |
          ls -lha build

      - name: store built file
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build
          
