name: termux-root-3
on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/termux-root-3.yml'
  workflow_dispatch:
env:
  TERMUX_ARCH: aarch64
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: download archives
        run: |
          wget -nv \
            https://github.com/kawanakaiku/test-ci/releases/download/chroot-termux/system-${TERMUX_ARCH}.tar.xz \
            https://github.com/kawanakaiku/test-ci/releases/download/chroot-termux/termux-files-${TERMUX_ARCH}.tar.xz
      - name: extract
        run: |
          mkdir root
          cd root
          tar xf ../system-${TERMUX_ARCH}.tar.xz
          install -d -m 700 data/data/com.termux/{files,cache}
          tar xf ../termux-files-${TERMUX_ARCH}.tar.xz -C data/data/com.termux/files
      - name: archive
        run: |
          cd root
          tar -c -I 'xz -9 -T0' -f ../termux-${{ env.TERMUX_ARCH }}.tar.xz *
      - name: store
        uses: actions/upload-artifact@v3
        with:
          name: termux-${{ env.TERMUX_ARCH }}
          path: termux-${{ env.TERMUX_ARCH }}.tar.xz
