name: test_ubuntu

on:
    push:
      branches: [ main ]
      paths:
        - 'test_ubuntu/**'
        - '.github/workflows/test_ubuntu.yml'
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 1
  
    steps:
      - uses: actions/checkout@v3

      - name: get storage info
        run: |
            free -h
            df -h
            
      - name: Run a multi-line script
        run: |
            # sudo apt-get install -y --no-install-recommends ncdu
            # sudo ncdu -o ubuntu-22.04.ncdu /
            # 7z a -mx=9 ubuntu-22.04.ncdu.7z ubuntu-22.04.ncdu
            # bash test_ubuntu/main.sh
            
            bash <<'EOF'
            ls
            EOF
            
      - name: Cache build
        id: cache-build
        uses: actions/cache@v3
        with:
          path: ./test1
          key: test1
          
      - name: ncdu
        run: |
            sudo ncdu -o root.ncdu /
            
      - name: Store files
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ncdu
          path: root.ncdu
