name: test-debug-macos

on:
    workflow_dispatch:

jobs:
  build:
    runs-on: macos-12
  
    steps:
      - uses: actions/checkout@v3

      - name: main
        run: |
          grep -rl -e _ZNK3c1011DynamicType8fallbackEv /usr 2>stderr

      - name: error
        run: |
          cat stderr   
            
      - name: Waiting for debugger
        uses: mxschmitt/action-tmate@v3
            
 
