name: test_ubuntu

on:
    push:
      branches: [ main ]
      paths:
        - 'test_ubuntu/**'
        - '.github/workflows/test_ubuntu.yml'
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 300
  
    steps:
      - uses: actions/checkout@v3

      - name: packages
        run: |
            apt list --installed

      - name: get storage info
        run: |
            free -h
            df -h

      - name: get memory info
        run: |
            ps aux --sort -%mem

      - name: free space
        run: |
            set -o noglob
            sudo apt purge --auto-remove \
                ant \
                clang-* \
                dotnet-* \
                libllvm-* \
                man-db \
                mongodb-* \
                mono-* \
                monodoc-* \
                mysql-* \
                php* \
                postgresql-* \
                powershell \
                python2* \
                ruby* \
                sqlite3 \
                tex-* \
                vim-* \
                x11* 

            set -o noglob
            sudo rm -rf \
                /usr/local \
                /usr/local/lib/node_modules \
                /usr/local/lib/heroku \
                /usr/local/.ghcup \
                /usr/local/share/powershell \
                /usr/local/share/chromium \
                /usr/share/dotnet \
                /usr/share/swift \
                /usr/share/miniconda \
                /usr/share/az_* \
                /usr/share/gradle-* \
                /usr/share/miniconda \
                /usr/share/man \
                /usr/share/doc \
                /usr/lib/jvm \
                /usr/lib/google-cloud-sdk \
                /usr/lib/mono \
                /usr/lib/firefox \
                /usr/lib/mysql \
                /opt \
                /var/lib/docker \
                /home/{runner,runneradmin}/.{rustup,cargo,dotnet} \
                /home/linuxbrew \
                /etc/skel \
                /root/.sbt

      - name: packages
        run: |
            apt list --installed

      - name: get storage info
        run: |
            free -h
            df -h

      - name: get memory info
        run: |
            ps aux --sort -%mem
            
      - name: Run a multi-line script
        run: |
            # sudo apt-get install -y --no-install-recommends ncdu
            # sudo ncdu -o ubuntu-22.04.ncdu /
            # 7z a -mx=9 ubuntu-22.04.ncdu.7z ubuntu-22.04.ncdu
            # bash test_ubuntu/main.sh
            
            bash <<'EOF'
            ls
            EOF
            
      - name: Cache build
        id: cache-build
        uses: actions/cache@v3
        with:
          path: ./test1
          key: test1
          
      - name: ncdu
        run: |
          sudo apt-get install ncdu
          sudo ncdu -o root.ncdu /
            
      - name: Store files
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ncdu
          path: root.ncdu
