name: test-debug

on:
    workflow_dispatch:
    
env:
  env_1 : test_inline
  
jobs:
  build:
    runs-on: ubuntu-22.04
  
    steps:
      - uses: actions/checkout@v3

      - name: get storage info
        run: |
            free -h
            df -h
            
      - name: Run a multi-line script
        run: |
            . mod_apt.sh
            cat <<'EOF'
            '${{ env.env_1 }}'
            EOF
           
            
      - name: Waiting for debugger
        uses: mxschmitt/action-tmate@v3
            
 
