name: test_ubuntu

on:
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
  
    steps:
      - uses: actions/checkout@v3

      - name: get storage info
        run: |
            free -h
            df -h
      - name: Run a multi-line script
        run: |
            sudo apt-get install -y --no-install-recommends ncdu
            sudo ncdu -o ubuntu-22.04.ncdu
            7z a -mx=9 ubuntu-22.04.ncdu.7z ubuntu-22.04.ncdu
      - name: Store log files
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: archive
          path: ubuntu-22.04.ncdu.7z
