name: test-debug-windows

on:
    workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019
  
    steps:
      - uses: actions/checkout@v3
           
            
      - name: Waiting for debugger
        uses: mxschmitt/action-tmate@v3
            
 
