name: windows-2022

on:
    workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
  
    steps:
      - uses: actions/checkout@v3
           
            
      - name: Waiting for debugger
        uses: mxschmitt/action-tmate@v3
            
 
