name: yt-dlp-nuitka

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/yt-dlp-nuitka.yml'

jobs:
  build:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v3

      - name: Run a build script
        run: |
          python3.exe -m pip install -U nuitka ordered-set yt-dlp
          python3.exe -c 'import yt_dlp as y;print(y)'
          python3.exe -m nuitka --onefile --follow-imports C:\hostedtoolcache\windows\Python\3.7.9\x64\lib\site-packages\yt_dlp\__main__.py
          7z.exe a -mx=9 built.7z .
          
      - name: Store built files
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: built
          path: built.7z
