name: yt-dlp-nuitka

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/yt-dlp-nuitka.yml'

jobs:
  build:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v3

      - name: Run a build script
        run: |
          mkdir build ; cd build
          python3.exe -m pip install -U nuitka ordered-set yt-dlp
          python3.exe -m nuitka --standalone --follow-imports --prefer-source-code --assume-yes-for-downloads c:\hostedtoolcache\windows\python\3.9.13\x64\lib\site-packages\yt_dlp\__main__.py
          cd ..
          7z.exe a -mx=9 built.7z build
          
      - name: Store built files
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: built
          path: built.7z
